cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
  jpa:
    show-sql: true
  security:
    user:
      name: user
      password: pass
